version: "3"
services:
  mongo:
    image: mongo:3.2
    container_name: mongo
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - shared-volume:/db/lrs_db
    env_file:
      - ./.env
    networks:
      - local
    restart: always

  mongo_setup:
    image: mongo:3.2
    container_name: mongo_setup
    depends_on:
      - mongo
      - lrs
    networks:
      - local
    volumes:
      - shared-volume:/db/lrs_db
    restart: "no"
    entrypoint: [ "mongorestore", "--host", "mongo", "--db", "lrs_db", "--dir", "./db/lrs_db" ]

  lrs:
    image: sproutlabs/learninglocker
    container_name: lrs
    ports:
      - "80:80"
    env_file:
      - ./.env
    networks:
      - local
    restart: always
    depends_on:
      - mongo

  back:
    build: ./
    image: xapi_back
    container_name: back
    ports:
      - "127.0.0.1:4000:4000"
    env_file:
      - ./.env
    networks:
      - local
    restart: unless-stopped
    volumes:
      - shared-volume:/db/lrs_db
    depends_on:
      - mongo
      - lrs

  front:
    image: vendrik/xapi_front
    container_name: front
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - local
    restart: unless-stopped
    depends_on:
      - mongo
      - lrs

volumes:
  shared-volume:

networks:
  local:
    driver: "bridge"